#byxussofupdate find for a better solution than shell
- name: Git add changes to {{ git_branch }} branch on {{ git_repo_name }} repository
  shell: 'git add . --all'
  args:
    chdir: "{{ git_chdir }}"
  #byxussof make a fail when != Your branch is up to date with
  ignore_errors: true
#  when: with_commits == true
